// export let label = [
//   "uid",
//   "team",
//   "match",
//   "Alliance Color",
//   "Scouter Name",
//   "Starting Position",
//   "Auton Lower-Hub",
//   "Auton Upper-Hub",
//   "Teleop Lower-Hub",
//   "Teleop Upper-Hub",
//   "Shooting Position",
//   "Final Rung",
//   "Climb Speed",
//   "Intake Speed",
//   "Two Balls",
//   "Defense Played Upon",
//   "Notes",
//   "Defense Percentage",
//   "Defense Rating",
//   "Defense Notes",
//   "Robot Rating",
//   "Auton Points",
//   "Teleop Points",
//   "Endgame Points",
//   "Total Points",
// ];

export let label = [
  "uid",
  "match",
  "team",
  "Alliance Color",
  "Scouter Name",
  "Starting Position",
  "Auton Cones Lower",
  "Auton Cubes Lower",
  "Auton Cones Mid",
  "Auton Cubes Mid",
  "Auton Cones Upper",
  "Auton Cubes Upper",
  "Auton Charge Station",
  "Auton Notes",
  "Teleop Cones Lower",
  "Teleop Cubes Lower",
  "Teleop Cones Mid",
  "Teleop Cubes Mid",
  "Teleop Cones Upper",
  "Teleop Cubes Upper",
  "Piece Pickup",
  "Charge Station",
  "Station Side",
  "Under Defense",
  "Other Notes",
  "Defense Rating",
  "Defense Notes",
  "Robot Rating",
  "Auton Points",
  "Teleop Points",
  "Total Points",
];

export let pitLabel = [
  "uid",
  "scouter",
  "team",
  "Scouter Name",
  "Team Number",
  "Drivetrain",
  "Preferred Starting Position",
  "Shooting Preference",
  "Max Shot Position",
  "Climb",
  "Highest Rung",
  "Changes",
  "Notes",
];
