export let label = [
  "uid",
  "team",
  "match",
  "Alliance Color",
  "Scouter Name",
  "Starting Position",
  "Auton Lower-Hub",
  "Auton Upper-Hub",
  "Teleop Lower-Hub",
  "Teleop Upper-Hub",
  "Shooting Position",
  "Final Rung",
  "Climb Speed",
  "Intake Speed",
  "Two Balls",
  "Defense Played Upon",
  "Notes",
  "Defense Percentage",
  "Defense Rating",
  "Defense Notes",
  "Robot Rating",
  "Auton Points",
  "Teleop Points",
  "Endgame Points",
  "Total Points",
];

export let pitLabel = [
  "uid",
  "scouter",
  "team",
  "Scouter Name",
  "Team Number",
  "Drivetrain",
  "Preferred Starting Position",
  "Shooting Preference",
  "Max Shot Position",
  "Climb",
  "Highest Rung",
  "Changes",
  "Notes",
];
